micronaut:
  router:
    static-resources:
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
    versioning:
      enabled: true
  openapi:
    enabled: true
    responses:
      default:
        '400':
          description: "Bad Request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        '404':
          description: "Not Found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"