micronaut:
  application:
    name: employee-crud

datasources:
  default:
    url: jdbc:h2:mem:employeedb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ""
    schema-generate: CREATE_DROP
    dialect: H2

jpa:
  default:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  postgresql:
    url: jdbc:postgresql://localhost:5432/employeedb
    driverClassName: org.postgresql.Driver
    username: postgres
    password: password
    schema-generate: CREATE_DROP
    dialect: POSTGRES